version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/yapp
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root